base_url = "https://teadrinkingprogrammer.github.io/tranquil-demo"      # Domain name of your website
title = "tranquil"
description = "The demo site of zola theme tranquil"
default_language = "en"
theme = "tranquil"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feed = false                 # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filename = "feed.xml"            # The file name of feed, "feed.xml" / "atom.xml" / "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = false
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Tranquil Theme"                         # Your name
id = "tranquil"                           # Your id / username / handle
bio = "A blog theme for Zola, inspired by Serene, but built with Tailwind"                          # Your bio
avatar = "img/avatar.webp"            # Your avatar
links = [                             # Your links
    { name = "GitHub", icon = "github", url = "https://github.com/TeaDrinkingProgrammer" },
    # { name = "Twitter", icon = "twitter", url = "https://twitter.com/<your-username>" },
    { name = "Email", icon = "email", url = "mailto:<your-email-address>" },
]

homepage_layout = "about"             # "about" | "list"

sections = [
    { name = "blog", path = "/blog", is_external = false },
    { name = "projects", path = "/projects", is_external = false },
    # { name = "about", path = "/about", is_exteranl = false },
    # { name = "github", path = "https://github.com/<your-username>", is_exteranl = true },
]
blog_section_path = "/blog"

nav_separator = ">"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = true                     # Display your id on homepage
blog_categorized = false               # Whether to categorize blog posts
projects_page = true                  # Display projects page
back_to_top = true                    # Whether to show back-to-top button on post pages

toc = true                            # Whether to show Table-Of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2023 Tranquil"
footer_credits = true                 # Whether to show "Powered by Zola and Serene" in footer
