# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
        with:
          submodules: recursive
          token: ${{ secrets.TOKEN }}

      - name: Prebuild
        uses: oven-sh/setup-bun@v1
      - run: bun install
        working-directory: ./themes/tranquil
      - run: npx tailwindcss -i styles/styles.css -o static/styles/styles.css --minify
        working-directory: ./themes/tranquil
      - run: bun run partytown
        working-directory: ./themes/tranquil
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
